name: Build vCluster Platform
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io/loft-demos
  # github.repository as <account>/<repo>
  IMAGE_NAME: vcluster-platform
  VCLUSER_PRO_VERSION: "0.22.3"
  K8S_VERSION: "v1.31.4"

jobs:
  build-push-image:
    name: Build vCluster Platform
    runs-on: ubuntu-latest

    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.platform
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:4.2.2
          labels: 4.2.2
