name: Build vCluster with K8s
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io/loft-demos
  # github.repository as <account>/<repo>
  IMAGE_NAME: vcluster-pro
  VCLUSER_PRO_VERSION: "0.22.3"
  K8S_VERSION: "v1.31.4"

jobs:
  build-push-image:
    name: Build vCluster
    runs-on: ubuntu-latest

    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"

    strategy:
      fail-fast: false
      matrix:
        # runner_platform: [ { runner: 	ubuntu-24.04, platform: linux/amd64, architecture: amd64 }, { runner: 	ubuntu-24.04-arm, platform: linux/arm64, architecture: arm64 } ]
        vcluster-version:
          - "0.22.4"
          - "0.23.0-alpha.8"
        k8s-version:
          - "v1.29.13"
          - "v1.30.9"
          - "v1.31.5"
          - "v1.32.1"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.vcluster-version }}-k8s.${{ matrix.k8s-version }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VCLUSER_PRO_VERSION =${{ matrix.vcluster-version }}
            K8S_VERSION=${{ matrix.k8s-version }}
