name: Mirror K8s Images
on:
  workflow_dispatch:

jobs:
  release:
    name: Mirror Images
    runs-on: ubuntu-latest

    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"

    env:
      K8S_REGISTRY: "registry.k8s.io"
      REGISTRY: "ghcr.io/loft-demos"

    strategy:
      fail-fast: false
      matrix:
        image:
          - "kube-apiserver:v1.31.1"
          - "kube-apiserver:v1.30.5"
          - "kube-apiserver:v1.30.2"
          - "kube-apiserver:v1.29.6"
          - "kube-controller-manager:v1.31.1"
          - "kube-controller-manager:v1.30.5"
          - "kube-controller-manager:v1.30.2"
          - "kube-controller-manager:v1.29.6"
          - "kube-scheduler:v1.31.1"
          - "kube-scheduler:v1.30.5"
          - "kube-scheduler:v1.30.2"
          - "kube-scheduler:v1.29.6"

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Image from Docker Hub
        run: docker pull ${{ env.K8S_REGISTRY }}/${{ matrix.image }}

      - name: Tag Image
        run:
          docker tag ${{ env.K8S_REGISTRY }}/${{ matrix.image }} ${{ env.REGISTRY }}/${{ matrix.image }}

      - name: Push Image
        run:
          docker push ${{ env.REGISTRY }}/${{ matrix.image }}
